version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    tty: true
    network_mode: host
    extra_hosts:
      - "namenode:192.168.1.4"
      - "datanode:192.168.1.4"
    restart: always
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    tty: true
    network_mode: host
    extra_hosts:
      - "namenode:192.168.1.4"
      - "datanode:192.168.1.4"
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
